# Generated by Django 2.1.7 on 2019-03-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candid_name', models.CharField(max_length=50)),
                ('candid_posn', models.CharField(max_length=50)),
                ('votes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=50)),
                ('voter_id', models.CharField(max_length=10)),
                ('voter_passwd', models.CharField(max_length=20)),
            ],
        ),
    ]
