# Generated by Django 2.1.7 on 2019-03-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidates',
            options={'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='voters',
            options={'verbose_name_plural': 'Voters'},
        ),
        migrations.RenameField(
            model_name='positions',
            old_name='user_name',
            new_name='positn_name',
        ),
    ]
