# Generated by Django 2.0.5 on 2019-03-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190329_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='votes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
