# Generated by Django 2.1.7 on 2019-03-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190329_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='voter_num',
            field=models.CharField(default='8959636987', max_length=10),
        ),
    ]
