# Generated by Django 2.1.7 on 2019-04-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
