# Generated by Django 2.1.7 on 2019-05-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voters',
            name='id',
        ),
        migrations.AlterField(
            model_name='voters',
            name='voter_num',
            field=models.CharField(default='8959636987', max_length=10, primary_key=True, serialize=False),
        ),
    ]
