# Generated by Django 2.1.7 on 2019-07-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190501_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='voter_permit',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='No', max_length=3),
        ),
    ]
