# Generated by Django 2.1.7 on 2019-07-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_voters_voter_permit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='voter_permit',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
