# Generated by Django 2.1.7 on 2019-08-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20190703_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voters',
            options={},
        ),
    ]
